2022-03-27 22:28:19,847 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-03-27 22:28:19,847 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from /home/achyuth/.local/lib/python3.9/site-packages/instabot/bot/bot.py
2022-03-27 22:28:19,849 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-03-27 22:28:20,854 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2022-03-27 22:28:21,895 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-03-27 22:28:22,927 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-03-27 22:28:24,055 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2022-03-27 22:28:27,237 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2022-03-27 22:28:27,238 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXHGom4mytAlMaWeKTx9I5CMhuO7-goYX78ImvIF20hUcRIUlOpVIYc3vG603SkPBiB2f4c/aH5nAbWvOVtGiD2s/","api_path":"/challenge/AXHGom4mytAlMaWeKTx9I5CMhuO7-goYX78ImvIF20hUcRIUlOpVIYc3vG603SkPBiB2f4c/aH5nAbWvOVtGiD2s/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2022-03-27 22:28:27,238 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2022-03-27 22:28:27,238 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2022-03-27 22:28:27,239 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
2022-03-27 22:28:31,745 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2022-03-27 22:28:31,748 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'demo.jpg' is not uploaded.
